# Generated by Django 5.0.4 on 2024-05-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0002_servicedetail_link_title2_servicedetail_link_url2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceDetail',
        ),
    ]
