# Generated by Django 5.0.4 on 2024-05-02 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0004_catagori'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='catagori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Seyahat.catagori'),
        ),
    ]
