# Generated by Django 5.0.4 on 2024-05-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0005_service_catagori'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='catagori',
            new_name='Catagori',
        ),
    ]
