# Generated by Django 5.0.4 on 2024-05-03 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0006_rename_catagori_service_catagori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagori',
            name='slug',
        ),
    ]
