# Generated by Django 5.0.4 on 2024-05-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0007_remove_catagori_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media')),
                ('description', models.TextField()),
                ('link_title', models.CharField(blank=True, max_length=100)),
                ('link_url', models.URLField(blank=True)),
                ('link_title2', models.CharField(blank=True, max_length=100)),
                ('link_url2', models.URLField(blank=True)),
                ('main_title1', models.CharField(max_length=200)),
                ('title1', models.CharField(max_length=200)),
                ('image1', models.ImageField(upload_to='media')),
                ('description1', models.TextField()),
                ('main_title2', models.CharField(max_length=200)),
                ('title2', models.CharField(max_length=200)),
                ('image2', models.ImageField(upload_to='media')),
                ('description2', models.TextField()),
            ],
        ),
    ]
