# Generated by Django 5.0.4 on 2024-05-03 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0009_remove_servicedetail_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceDetail',
        ),
    ]
