# Generated by Django 5.0.4 on 2024-05-03 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0010_delete_servicedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('link_title', models.CharField(blank=True, max_length=100)),
                ('link_url', models.URLField(blank=True)),
                ('link_title2', models.CharField(blank=True, max_length=100)),
                ('link_url2', models.URLField(blank=True)),
                ('main_title1', models.CharField(max_length=200)),
                ('title1', models.CharField(max_length=200)),
                ('image1', models.ImageField(upload_to='media')),
                ('description1', models.TextField()),
                ('main_title2', models.CharField(max_length=200)),
                ('title2', models.CharField(max_length=200)),
                ('image2', models.ImageField(upload_to='media')),
                ('description2', models.TextField()),
                ('Catagori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Seyahat.catagori')),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
