# Generated by Django 5.0.4 on 2024-05-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0020_servicedetail_catagori'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='GezilecekYer1',
            field=models.CharField(default='Gezilecek Yer 1', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='GezilecekYer2',
            field=models.CharField(default='Gezilecek Yer 2', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='GezilecekYer3',
            field=models.CharField(default='Gezilecek Yer 3', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='GezilecekYer4',
            field=models.CharField(default='Gezilecek Yer 4', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='description_1',
            field=models.TextField(default='Açıklama 1'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='description_2',
            field=models.TextField(default='Açıklama 2'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='description_3',
            field=models.TextField(default='Açıklama 3'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='description_4',
            field=models.TextField(default='Açıklama 4'),
        ),
    ]
