# Generated by Django 5.0.4 on 2024-05-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0021_servicedetail_gezilecekyer1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='link_title',
        ),
        migrations.RemoveField(
            model_name='services',
            name='link_title2',
        ),
        migrations.RemoveField(
            model_name='services',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='services',
            name='link_url2',
        ),
        migrations.RemoveField(
            model_name='services',
            name='main_title',
        ),
        migrations.RemoveField(
            model_name='services',
            name='main_title2',
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='GezilecekYer1',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='GezilecekYer2',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='GezilecekYer3',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='GezilecekYer4',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='description_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='description_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='description_3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='description_4',
            field=models.TextField(),
        ),
    ]
