# Generated by Django 5.0.4 on 2024-05-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0023_servicedetail_link_title_servicedetail_link_title2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='link_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='link_title2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='link_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='link_url2',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='main_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='main_title2',
            field=models.CharField(max_length=200),
        ),
    ]
