# Generated by Django 5.0.4 on 2024-05-15 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0025_remove_services_catagori'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='Catagori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Seyahat.catagori'),
        ),
    ]
