# Generated by Django 5.0.4 on 2024-05-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0026_services_catagori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetail',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='title2',
        ),
    ]
