# Generated by Django 5.0.4 on 2024-05-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0027_remove_servicedetail_description1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200)),
                ('image1', models.ImageField(upload_to='media')),
                ('description1', models.TextField()),
                ('title2', models.CharField(max_length=200)),
                ('image2', models.ImageField(upload_to='media')),
                ('description2', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='adreslink1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='adreslink2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='adreslink3',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='adreslink4',
            field=models.URLField(blank=True),
        ),
    ]
