# Generated by Django 5.0.4 on 2024-05-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0031_servicedetail_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetail',
            name='GezilecekYer1',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='GezilecekYer2',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='GezilecekYer3',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='GezilecekYer4',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='adreslink1',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='adreslink2',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='adreslink3',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='adreslink4',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='description_1',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='description_4',
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
