# Generated by Django 5.0.4 on 2024-05-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0032_remove_servicedetail_gezilecekyer1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='gezilecekyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('GezilecekYer1', models.CharField(max_length=200, unique=True)),
                ('description_1', models.TextField()),
                ('adreslink1', models.URLField(blank=True)),
                ('GezilecekYer2', models.CharField(max_length=200, unique=True)),
                ('description_2', models.TextField()),
                ('adreslink2', models.URLField(blank=True)),
                ('GezilecekYer3', models.CharField(max_length=200, unique=True)),
                ('description_3', models.TextField()),
                ('adreslink3', models.URLField(blank=True)),
                ('GezilecekYer4', models.CharField(max_length=200, unique=True)),
                ('description_4', models.TextField()),
                ('adreslink4', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='servicic',
            name='link_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicic',
            name='link_url',
            field=models.URLField(blank=True),
        ),
    ]
