# Generated by Django 5.0.4 on 2024-05-23 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0033_gezilecekyer_servicic_link_title_servicic_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gezilecekyer',
            name='GezilecekYer2',
        ),
        migrations.RemoveField(
            model_name='gezilecekyer',
            name='GezilecekYer3',
        ),
        migrations.RemoveField(
            model_name='gezilecekyer',
            name='GezilecekYer4',
        ),
        migrations.RemoveField(
            model_name='gezilecekyer',
            name='adreslink2',
        ),
        migrations.RemoveField(
            model_name='gezilecekyer',
            name='adreslink3',
        ),
        migrations.RemoveField(
            model_name='gezilecekyer',
            name='adreslink4',
        ),
        migrations.RemoveField(
            model_name='gezilecekyer',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='gezilecekyer',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='gezilecekyer',
            name='description_4',
        ),
    ]
