# Generated by Django 5.0.4 on 2024-05-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0035_gezilecekdetai_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicic',
            old_name='link_title',
            new_name='link_title2',
        ),
        migrations.RenameField(
            model_name='servicic',
            old_name='link_url',
            new_name='link_url1',
        ),
        migrations.AddField(
            model_name='servicic',
            name='link_title1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicic',
            name='link_url2',
            field=models.URLField(blank=True),
        ),
    ]
