# Generated by Django 5.0.4 on 2024-05-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0037_gezilecekdetai_gezilecekyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gezilecekdetai',
            name='gezilecekyer',
        ),
    ]
