# Generated by Django 5.0.4 on 2024-05-25 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0039_gezilecekdetai_gezilecekyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gezilecekyer',
            name='service_detail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='gezilecek_yerler', to='Seyahat.servicedetail'),
        ),
    ]
