# Generated by Django 5.0.4 on 2024-05-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0041_servicedetail_service_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetail',
            name='service_detail',
        ),
    ]
