# Generated by Django 5.0.4 on 2024-05-27 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0042_remove_servicedetail_service_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='gezilecekdetai',
            name='service_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gezilecekdetai', to='Seyahat.servicedetail'),
        ),
    ]
