# Generated by Django 5.0.4 on 2024-05-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0043_gezilecekdetai_service_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gezilecekdetai',
        ),
    ]
