# Generated by Django 5.0.4 on 2024-05-30 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0046_gezilecekyerdetai_detai_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('service_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='Seyahat.servicedetail')),
            ],
        ),
    ]
