# Generated by Django 5.0.4 on 2024-05-30 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0047_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='service_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Seyahat.servicedetail'),
        ),
    ]
