# Generated by Django 5.0.4 on 2024-05-03 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websi', '0002_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpage',
            name='index_description',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='index_image',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='index_title',
        ),
    ]
