# Generated by Django 5.0.4 on 2024-05-17 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websi', '0004_indexpage_why_choose_us_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='timestamp',
        ),
    ]
