# Generated by Django 5.0.4 on 2024-05-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websi', '0008_alter_contactmessage_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='phone_number',
        ),
    ]
